Refactor Symop to be multiple classes
pace-neutrons/Horace pull request #1008
Opened 2023-04-06 18:35 UTC by oerc0122

2023-04-12 10:06 UTC, cmarooney-stfc requested changes

2023-04-12 12:21 UTC, oerc0122 commented on horace_core/symop/@Symop/Symop.m
> +            obj.W_ = reshape(val, [3 3]);
It just needs to have 9 elements in any shape as defined by `is_3x3matrix` (requires `isnumeric && numel == 9`)

2023-04-12 13:37 UTC, cmarooney-stfc commented on horace_core/symop/@Symop/Symop.m
> +            obj.W_ = reshape(val, [3 3]);
```suggestion
            obj.W_ = reshape(val, [3 3]); % as tested by is_3x3matrix
```

2023-06-26 14:51 UTC, cmarooney-stfc requested changes

2023-06-26 14:51 UTC, cmarooney-stfc commented on horace_core/sqw/@SQWDnDBase/private/cut_parse_inputs_.m
> +%   >> sym_out = cut_sqw_check_sym_arg (sym)
check name

2023-06-26 14:51 UTC, cmarooney-stfc commented on horace_core/sqw/@SQWDnDBase/private/cut_parse_inputs_.m
> +% Always return identity
```suggestion
% Always add identity in addition to other kept symops
```

2023-06-26 14:51 UTC, cmarooney-stfc commented on horace_core/symop/@Symop/Symop.m
> +    end
did not read Dependent correctly, this is ok

2023-06-26 14:51 UTC, cmarooney-stfc commented on horace_core/symop/@Symop/Symop.m
> +                       'Received: %s'], disp2str(W));
fixed by JW

2023-06-26 14:51 UTC, cmarooney-stfc commented on horace_core/symop/@Symop/Symop.m
> +        end
fixed by JW

2023-06-26 14:51 UTC, cmarooney-stfc commented on horace_core/symop/@Symop/Symop.m
> +            if isscalar(obj)
L 127 fixes

2023-06-26 14:51 UTC, cmarooney-stfc commented on horace_core/symop/@Symop/Symop.m
> +        %       >> obj = Symop.create (u, v, offset)
by argument types (jw)

2023-06-28 13:12 UTC, merged