1002 cut sym
pace-neutrons/Horace pull request #1017
Opened 2023-05-02 12:47 UTC by oerc0122

Add cut_sym with symops

2023-05-03 13:56 UTC, cmarooney-stfc commented on herbert_core/utilities/maths/merge_ranges.m
> +% single block of starts, lengths eliminating overlap.
```suggestion
% single block of starts, lengths eliminating any overlap between adjacent intervals to create a single compound interval from any set of overlapping integrals.
```

2023-05-04 10:52 UTC, oerc0122 commented on horace_core/sqw/@SQWDnDBase/private/cut_parse_inputs_.m
> +%                  by which a symmetry related cut is to be accumulated.
The function is called `cut_accumulate_data_` so I presume it's a known thing in the field.

2023-06-06 14:34 UTC, oerc0122 commented on horace_core/sqw/@sqw/private/cut_accumulate_data_.m
> +if ~cut_to_file && PixelDataBase.do_filebacked(n_candidate_pix, 10)
Yes, I did. I want the warning to happen if it would fail over 10*mem_chunk_size

2023-06-06 14:39 UTC, cmarooney-stfc requested changes

2023-06-06 14:39 UTC, cmarooney-stfc commented on horace_core/sqw/@SQWDnDBase/private/cut_parse_inputs_.m
> +%           are removed from the cell array.
presuming this is a subset of the input argument, but you don't say so

2023-06-06 14:39 UTC, cmarooney-stfc commented on horace_core/sqw/@sqw/private/cut_accumulate_data_.m
> +    [block_starts, block_sizes] = arrayfun(@(proj, ax) sproj.get_nrange(obj.data.npix, saxes, ax, proj), ...
sorry I had not noticed that these are also input arguments to line 60

2023-06-06 14:41 UTC, oerc0122 commented on horace_core/horace_function_utils/private/is_horace_data_file_opt.m
> +opt_hor=strcmpi(opt,'$hor');
I wanted to do this as it doesn't matter if it's `char` or `string` and `strcmpi` is perfectly happy with `strcmpi(13, 'hello')` so it's not a problem.

2023-06-08 15:26 UTC, merged