Update compact to new sqw/dnd style
pace-neutrons/Horace pull request #1043
Opened 2023-06-16 11:46 UTC by oerc0122

Fix compact for eliminating empty edge-bins 

Fixes #1023

2023-06-16 14:02 UTC, cmarooney-stfc requested changes

2023-06-16 14:02 UTC, cmarooney-stfc commented on horace_core/sqw/@DnDBase/compact.m
> +% Squeezes the data range in a dnd object to eliminate empty bins
```suggestion
% Squeezes the data range in a dnd object or array of such objects to eliminate empty bins
```

2023-06-16 14:02 UTC, cmarooney-stfc commented on horace_core/sqw/@DnDBase/compact.m
> +%   din         Input object
```suggestion
%   din         Input object(s)
```

2023-06-16 14:02 UTC, cmarooney-stfc commented on horace_core/sqw/@DnDBase/compact.m
> +%   dout        Output object, with length of axes reduced to yield the
```suggestion
%   dout        Output object(s), with length of axes reduced to yield the
```

2023-06-16 14:02 UTC, cmarooney-stfc commented on horace_core/sqw/@DnDBase/compact.m
> +%               smallest cuboid that contains the non-empty bins.
```suggestion
%               smallest cuboid for each input object that contains the non-empty bins.
```

2023-06-22 14:52 UTC, abuts reviewed
This blows my mind. I do not understsand if it works or not. e.g. len(din(n).p) can not be zero. p is derived property of `nbin_all_dims`.
Need at least some unit tests.

As small note. I would add abstract compact to `SQWDnDBase` to have common interface for `sqw` and `DnD` objects -- further relocation is good

2023-07-07 15:44 UTC, cmarooney-stfc requested changes

2023-07-07 15:44 UTC, cmarooney-stfc commented on horace_core/sqw/@sqw/compact.m
> +% Squeezes the data range in an sqw or dnd object to eliminate empty bins
do you mean empty bins at the extrema of the ranges only? does not sound as if internal empty bins get eliminated.

the declaration agrees with this

2023-07-17 10:28 UTC, cmarooney-stfc requested changes

2023-07-17 10:28 UTC, cmarooney-stfc commented on horace_core/sqw/@sqw/compact.m
> +% Particularly of use for contracting dnds for plotting
not sure about this as this function contracts sqws.

2023-07-17 10:28 UTC, cmarooney-stfc commented on horace_core/sqw/@sqw/compact.m
> +%   win         Input object
```suggestion
%   win         Input sqw object
```

2023-07-17 10:28 UTC, cmarooney-stfc commented on horace_core/sqw/@DnDBase/compact.m
> +%   din         Input object(s)
```suggestion
%   din         Array of input object(s)
```

2023-07-17 10:28 UTC, cmarooney-stfc commented on horace_core/sqw/@DnDBase/compact.m
> +%   dout        Output object(s), with length of axes reduced to yield the
```suggestion
%   dout        Scalar output object or cell array of output object(s), with length of axes reduced to yield the
```

2023-07-17 10:28 UTC, cmarooney-stfc commented on horace_core/sqw/@DnDBase/compact.m
> +%
An equivalent method is provided for the sqw class to compact its dnd sub-objects

2023-07-17 14:04 UTC, cmarooney-stfc approved these changes

2023-07-17 14:06 UTC, cmarooney-stfc approved these changes

2023-07-24 10:14 UTC, merged