First pass using temporaries
pace-neutrons/Horace pull request #1053
Opened 2023-06-20 12:25 UTC by oerc0122

Make tests use temporary setting functions

Fixes #965

2023-06-22 13:39 UTC, cmarooney-stfc requested changes

2023-06-26 10:41 UTC, oerc0122 commented on _test/common_functions/@SQW_GENCUT_perf_tester/SQW_GENCUT_perf_tester.m
> +            clob = onCleanup(@()(0));
Because the caller demands an `onCleanup` object is returned from this function, this null op is returned to say `Do nothing`

2023-06-26 10:44 UTC, oerc0122 commented on _test/test_gen_sqw_workflow/gen_sqw_accumulate_sqw_tests_common.m
> +                                               );
Savable `false` is set in `set_temporary_config_options` as a matter of course

2023-06-26 10:45 UTC, oerc0122 commented on _test/test_mex_nomex/test_dummy_sqw_bin_pix.m
> +            cleanup_obj_hc = set_temporary_config_options(hor_config, 'use_mex', true);
They're stored, but never set in this function, so it does nothing anyway.

2023-07-04 12:36 UTC, merged