Remove old serialiser
pace-neutrons/Horace pull request #1064
Opened 2023-06-26 10:20 UTC by oerc0122

Remove old serialisation routines (`hlp_serialize`, `hlp_deserialize`, `hlp_serial_size`) and rename new routines (`hlp_serialise`, `hlp_deserialise`, `hlp_serial_sise`) to use `z` spelling

2023-06-30 10:30 UTC, cmarooney-stfc requested changes

2023-06-30 10:30 UTC, cmarooney-stfc commented on herbert_core/utilities/misc/hlp_serial_size.m
> +        error(['Cannot serial_size ', type.name]);
Not standard error spec

2023-06-30 10:38 UTC, oerc0122 commented on _test/test_serializers/test_serialize.m
> +classdef test_serialize < TestCase
No, this is just that `test_serialize` was overwritten by `test_serialise`. Will update

2023-07-03 13:06 UTC, cmarooney-stfc requested changes

2023-07-03 14:59 UTC, oerc0122 commented on _test/test_serializers/test_serialize_size.m
> +            assertEqual(numel(ser), ser_siz)
Null ([0x0]) vs. Empty ([1x1]) is consistent for other tests in the series (see sparse), the distinction in names is, to me, unimportant but clearly separate. 

The test is merely ensuring that the `serial_size` *is* what the serializer returns, as such if we update the serializer in the future to, for example,  add extra tags, this checks it corresponds, NOT that its value should be 1. Hence the test against the integer would change what the test tests.

2023-07-04 12:29 UTC, merged