File-back `get_nearest_pixels` and remove `calc_uproj_pix`
pace-neutrons/Horace pull request #1128
Opened 2023-07-18 10:46 UTC by oerc0122

- Adds two new methods to `AxesBlockBase` to extract step lengths and bin arbitrary points
- Cleans up and filebacks `get_nearest_pixels` (used in `resolution_plot`) and removes `calculate_uproj_pix` as this is now on `aProjection` objects.

Fixes #1114

2023-07-21 10:47 UTC, abuts commented on horace_core/sqw/axes_blocks/@AxesBlockBase/AxesBlockBase.m
> +        end
I believe, step should be 
```
steps = (max_val-min_val)/(nbins-1)
```
fitst point is `min_val`, last point at nbins is: 
`x_nbins = min_val + step*(nbins-1) == max_val`

2023-07-21 11:05 UTC, abuts commented on horace_core/sqw/axes_blocks/@AxesBlockBase/AxesBlockBase.m
> +        end
As this will lead to inf for nbins == 0, steps should be along the projection axes only i.e. `obj.img_range(2,obj.pax)`

2023-07-21 11:12 UTC, abuts commented on horace_core/sqw/@sqw/get_nearest_pixels.m
> +    curr_pix = win.pix.get_pix_in_ranges(nbeg(ind(i)), npix(ind(i)));
This will give only one (current) bin. One should consider all bins adjusent to current, and keep in mind the situation if they all empty

2023-07-21 11:48 UTC, abuts requested changes
I belive, step size is defined incorrectly so this needs to be fixed. 
Everything else rises questions to the original algorithm -- I do not think it was giving the correct answers in any case. 
The changes look fine, though further improvement is necessary

2023-07-25 10:29 UTC, cmarooney-stfc requested changes

2023-07-25 10:29 UTC, cmarooney-stfc commented on _test/test_transformation/test_ortho_axes.m
> +            idx = ab.bin_points([5 -5 0 0
```suggestion
            idx = ab.bin_points([5 -5 0 0;
```

2023-07-25 10:48 UTC, cmarooney-stfc commented on horace_core/sqw/axes_blocks/@AxesBlockBase/AxesBlockBase.m
> +                      'Cannot bin point with different dimensionality.')
```suggestion
                      'Cannot bin points with different dimensionality to the axes block.')
```

2023-07-25 15:18 UTC, merged