IX_experiment objects modified for comparison
pace-neutrons/Horace pull request #1158
Opened 2023-07-31 13:49 UTC by abuts

This is part of #748 accumulate sqw  ticket (incomplete)
Here I've modified IX_experiment to have partial hash operation for objects comparison.

Next step would be actual comparison and accumulate operation enabled

2023-08-01 16:03 UTC, oerc0122 requested changes

2023-08-01 16:03 UTC, oerc0122 commented on herbert_core/classes/instrument_classes/@goniometer/goniometer.m
> +    % or:
All of this is about `oriented_lattice` not `goniometer`

2023-08-01 21:53 UTC, abuts commented on _test/test_instrument_classes/test_goniometer.m
> +            ol=ol.set_deg();
there is such a property. Its legacy interface. Provanly worth removing

2023-08-02 09:33 UTC, oerc0122 commented on _test/test_instrument_classes/test_goniometer.m
> +            ol=ol.set_deg();
Which are you saying is worth removing? The `set_deg`, `set_rad`?

2023-08-03 15:00 UTC, abuts commented on _test/test_instrument_classes/test_goniometer.m
> +            ol=ol.set_deg();
removed

2023-08-03 15:19 UTC, abuts commented on _test/test_unique_objects_container/test_unique_references.m
> +        function test_unique_reference_non_pollute_ws(obj)
workspace

2023-08-03 15:23 UTC, abuts commented on herbert_core/classes/instrument_classes/@goniometer/goniometer.m
> +        % ANGULAR TRANSFORMATIONS (is it necessary? A bit overcomplecated
This will make things even more convoluted

2023-08-03 15:24 UTC, abuts commented on herbert_core/classes/instrument_classes/@goniometer/goniometer.m
> +classdef goniometer < serializable
I belive, the goniometer on an instrument is the device to set up the sample orientation.  Class name stolen from similar in Mantid.

2023-08-03 15:25 UTC, abuts commented on herbert_core/classes/instrument_classes/@goniometer/private/check_angular_units_present_.m
> +    if numel(varargin)>=pos_deg && ischar(varargin{pos_deg}) && ismember(varargin{pos_deg},{'deg','rad'})
will not work, text will throw in `ismember`

2023-08-03 15:29 UTC, abuts commented on herbert_core/classes/instrument_classes/@goniometer/private/check_angular_units_present_.m
> +    is_ang = cellfun(@(x)ischar(x)&&strncmp(x,'angular_units',numel(x)),argi);
want to introduce partial key matching. May be on 3 symbol

2023-08-03 15:34 UTC, abuts commented on herbert_core/classes/instrument_classes/instrument/@IX_experiment/IX_experiment.m
> +            end
its called at least 500 times during sqw generation. Do not like it but honestly, do not know.

2023-08-03 15:37 UTC, abuts commented on herbert_core/classes/instrument_classes/instrument/@IX_experiment/IX_experiment.m
> +            for i=1:n_par
as the comparison is on selection of properties, and I am not sure if it is comprehencive, serializing it through standard means looks overcomplicated.

2023-08-03 15:38 UTC, abuts commented on herbert_core/utilities/classes/@unique_objects_container/unique_objects_container.m
> +            end
here it is certainly necessary. there are thouthend unique objects genreated during the session so signle processor would be certainly beneficial.

2023-08-03 17:13 UTC, abuts commented on horace_core/sqw/PixelData/@pix_combine_info/pix_combine_info.m
>              end
When I start thinking if the suggested statement is equivalen to the existing statement and spend more then 1 min on understanding this, it means it not worth it.

2023-08-03 17:16 UTC, oerc0122 commented on horace_core/sqw/PixelData/@pix_combine_info/pix_combine_info.m
>              end
How about if I rewrite it as:
```
if isempty(remains)
    % Continue
else if numel(remains) == 1
    obj.filenum_ = remains{1};
    return;
else
     error('HORACE:pix_combine_info:invalid_argument',[ ...
                        'pix_combine_info accepts up to 7 input arguments.\n' ...
                        'got: %d arguments. Last have not been recognized: %s\n'], ...
                        numel(varargin),disp2str(remains))
end
```

2023-08-04 15:33 UTC, merged