Fix alignment issues in both fb and mb forms
pace-neutrons/Horace pull request #1196
Opened 2023-08-22 10:59 UTC by oerc0122

- Use apply rather than separate function
- Add (logging) printing to apply

2023-08-23 08:22 UTC, cmarooney-stfc requested changes

2023-08-23 08:22 UTC, cmarooney-stfc commented on horace_core/sqw/@sqw/apply_alignment.m
> +                'Can not replace old file %s with new file %s. Continuing with new file', ...
```suggestion
                'Can not replace old file %s with new file %s. Continuing with old file', ...
```

2023-09-11 09:44 UTC, abuts reviewed
need to familarize myself more with `apply` Otherwise, alignment looks incorrect as data ranges are not initalized properly while assigning to data

2023-09-12 10:08 UTC, abuts commented on horace_core/sqw/PixelData/@PixelDataFileBacked/apply.m
I am working on fixing issue with data range, but to make current code reasobavle, the following change should be done to `apply`, rows 89-90 (new file):
```
        obj.data_range = ...
obj.pix_minmax_ranges(curr_pix.data, obj.data_range_)
```
(add underscore to exisitng data range)

2023-09-12 10:27 UTC, oerc0122 commented on horace_core/sqw/PixelData/@PixelDataFileBacked/apply.m
Is that including if we nullify the `data_range` at the start of the operation?

E.g. l. 108
```
obj.data_range = PixelDataBase.EMPTY_RANGE;
```

2023-09-12 10:32 UTC, abuts commented on horace_core/sqw/PixelData/@PixelDataFileBacked/apply.m
Initial nulification looks fine. Problems with 89-90 is that currently call to obj.data_range will cause recalculation of the whole data range. 
This will be changed in a nearest future, but meanwhile accessing private member will achieve the desirable goal.

2023-09-12 10:33 UTC, oerc0122 commented on horace_core/sqw/PixelData/@PixelDataFileBacked/apply.m
Updated, will that be ok?

2023-09-13 09:46 UTC, abuts approved these changes
looks fine for me

2023-09-13 12:46 UTC, cmarooney-stfc approved these changes

2023-09-13 13:38 UTC, merged