Test herbert replicate_array; cannot test horace version
pace-neutrons/Horace pull request #1284
Opened 2023-09-18 16:47 UTC by cmarooney-stfc

Visual inspection of the 2 replicate_array methods in horace and herbert indiciate that they have identical functionality although they are differently implemented; one uses an array_func to make individual replicas which are concatenated, while the other makes a large array, works out the replica positions and fills them.

This PR provides a test for the herbert version. The horace version is tested similarly by providing a public static interface function in the sqw.m file itself. It may be that this needs to be retired after this testing to preserve the integrity of the sqw class.

Alex claims that the horace version is twice as fast. Additional timings for this test suggest that for this size test the timing can vary either way so that issue is not dealt with here.

2023-09-26 17:38 UTC, abuts requested changes
I think we have verified the code and have proved that the version which is in `@sqw/private` is less efficient then one in `math/utilities`. 
The private version should go and everything should go through the public version. 
They are equivalent otherwise -- no point of keeping less efficient version

2024-02-09 08:51 UTC, tgperring commented
I think this PR is redundant. While doing a code review of a PR from Jacob recently I saw he had used a matlab intrinsic function repelem (introduced in R2015b) that performs in essence the same function as replicate_array, replicate_iarray and replicate_logarray. I performed fairly comprehensive timing tests and found that depending on input arguments it is anywhere between a factor 1 and 25 times faster than the faster of the two replicate_array versions here (which is in turn anywhere between a factor of 2 and 8 times faster than the slower version). I've updated ticket #848 with more details.

2024-02-09 09:16 UTC, abuts commented
The changes are not about `repelem`. Here you combine multiple chunks in a single array, i.e. multiple pixel data arrays into signle pixel array. There are two ways of doing this: create chunks and `concat` them or allocate whole array and place chunks into appropriate positions. We have identified that the second way is faster and here we need to change code to use faster method.

2024-02-09 11:25 UTC, tgperring commented
Alex, I don't understand your comment. I know that this PR and the ticket #848 are about the function replicate_array, which exists in two places, and work by two methods. In my comment here (and which is elaborated upon in a comment I have added to #848) what I am doing is pointing out that what the function replicate_array does is identical to what the matlab intrinsic function repelem does, and which in fact does it much faster. On my laptop, it is up to 25 times faster than the Herbert version, and up to 200 times faster than the sqw/private version). We don't need to know how it is doing the job, just that it is identical.

More specifically, and subject to checking of edge cases, any call to replicate_array:
:
vout = replicate_array (v, n)
:
can be replaced by:
:
vout = repelem (v(:), n(:))
:

Therefore this PR, whose sole purpose is to add a test routine to check the equivalence of the herbert and sqw/private versions of replicate_iarray is obsolete; the test is simply irrelevant. In a separate branch in reference to ticket #848, we can delete the sqw/private version, keep only the herbert version and replace its internal code with a single line making a call to repelem as above. Unit tests can be added on the same branch. The same can be done to replicate_iarray and replicate_logarray. These functions then become legacy functions and in the future we can just call repelem directly instead.

2024-02-12 10:05 UTC, closed without merging

2024-02-12 10:06 UTC, cmarooney-stfc commented
Superseded by PR #1543