Modified single page op
pace-neutrons/Horace pull request #1310
Opened 2023-10-05 13:38 UTC by abuts

The `apply_c` code modified for simplicity, some changes from prototype review are applied, design complete.

2023-10-05 16:17 UTC, cmarooney-stfc requested changes

2023-10-05 16:17 UTC, cmarooney-stfc commented on horace_core/utilities/compute_bin_data.m
> +%            only. If provided, variance have to be provided (may be empty, not to use it)
this sentence does not make sense

2023-10-06 18:52 UTC, abuts commented on horace_core/sqw/PixelData/@PixelDataFileBacked/PixelDataFileBacked.m
> +        % gets deleted
apparently, Matlab asignment for handle object increases ref counter so whatever surprizing it is, all works. 

I am unconsciously  using commas according to Russian rules, where sub-sentences are always separated by commas.

2023-10-06 18:54 UTC, abuts commented on horace_core/sqw/PixelData/@PixelDataFileBacked/PixelDataFileBacked.m
>              % row_pix_idx -- indixes of pixels to return
row and columt

2023-10-09 12:34 UTC, abuts commented on horace_core/sqw/PixelData/@PixelDataMemory/PixelDataMemory.m
>              % row_pix_idx -- indixes of pixels to return
row and column, raw pixels -- mentioned above

2023-10-09 12:36 UTC, abuts commented on horace_core/sqw/page_operations/PageOpBase.m
> +    % i.e. require rebinning or reordering of pixels.
definitions.  Two equivalend definitions made in different words. Whatever you like better -- they say the same thing

2023-10-09 12:45 UTC, abuts commented on horace_core/utilities/compute_bin_data.m
> +%            only. If provided, variance have to be provided (may be empty, not to use it)
? makes perfect sence to me.

2023-10-11 13:45 UTC, merged

2023-10-11 14:08 UTC, cmarooney-stfc requested changes

2023-10-11 17:35 UTC, abuts commented on horace_core/sqw/PixelData/@PixelDataFileBacked/PixelDataFileBacked.m
> +            obj = finish_dump_(obj);
I do not see reason why we should not.