Add Matlab wrapper to allow legacy to new multifit
pace-neutrons/Horace pull request #1369
Opened 2023-11-02 16:10 UTC by oerc0122

Add short wrapper script into `admin` to be able to call converter from Matlab

Fixes #1234

2023-11-02 16:22 UTC, mducle commented on admin/mf_leg_to_new.m
> +    conv = py.mf_leg_to_new.convert_legacy_multifit(funcline);
A nicer output might be:

```suggestion
    convstr = strip(char(py.mf_leg_to_new.convert_legacy_multifit(funcline)));
    if nargout < 1
        disp(convstr)
    else
        conv = convstr;
    end
```

2023-11-02 17:05 UTC, mducle approved these changes

2023-11-03 10:05 UTC, mducle requested changes
Actually I just realised that the `admin/` folder is not added to the Matlab path when you do `horace_init` (or `horace_on` on IDAaaS). So it would be best to put this file in another folder which is on the path, like `horace_core/utilities`

2023-11-03 10:59 UTC, abuts commented
There is another `admin` folder, located under `horace_core` (or `herbert_core`) this folder is added to the path while top admin is intended for devalopment and installation scripts

2023-11-03 11:01 UTC, abuts requested changes
move it to `horace_core\admin` folder and than it looks fine.

2023-11-03 13:53 UTC, mducle approved these changes

2023-11-06 10:07 UTC, cmarooney-stfc requested changes

2023-11-06 10:07 UTC, cmarooney-stfc commented on horace_core/admin/mf_leg_to_new.m
> +function conv = mf_leg_to_new(funcline)
```suggestion
function conv = mf_legacy_to_new(funcline)
```
Don't think missing out 3 chars is worth the uncertainty in meaning

2023-11-06 10:13 UTC, merged