Return error estimates from `refine_crystal`
pace-neutrons/Horace pull request #1381
Opened 2023-11-10 15:18 UTC by oerc0122

Return a structure from `refine_crystal` containing fit error estimates.

Fixes #770

2023-11-10 15:58 UTC, cmarooney-stfc requested changes
tests or otherwise needed to demonstrate use of the new argument

2023-11-13 11:21 UTC, abuts approved these changes
looks fine -- things are simple. Do you need a unit test for that?

2023-11-14 16:14 UTC, cmarooney-stfc requested changes

2023-11-14 16:14 UTC, cmarooney-stfc commented on _test/test_change_crystal/test_refine_crystal.m
> +        % Simple test to check whether err_est can be returned and
```suggestion
        % Simple test to check whether err_est can be returned by refine_crystal and
```

2023-11-14 16:14 UTC, cmarooney-stfc commented on _test/test_change_crystal/test_refine_crystal.m
> +        % is within acceptable range.
```suggestion
        % is within acceptable tolerance.
```

2023-11-23 14:04 UTC, cmarooney-stfc approved these changes

2023-11-23 14:05 UTC, merged