cat pixels and combine_sqw
pace-neutrons/Horace pull request #1385
Opened 2023-11-14 14:20 UTC by abuts

Depends on #1373 beeing merged.

This is partial solution of #1330 concerning cat pix and combine_sqw. Though combine sqw is not fully Page_op type operation, it would be difficult to implement if in other way then two-stage operation, combining pixels in big blob on the first stage.

This is what is done here.

2023-11-14 16:04 UTC, cmarooney-stfc requested changes

2023-11-15 19:38 UTC, abuts commented on horace_core/sqw/page_operations/PageOp_cat_pix.m
> +            is = ~isempty(obj.img_);
sqw object has image and pix does not.

2023-11-16 14:56 UTC, abuts commented on horace_core/configuration/@planner_config/planner_config.m
> +        function value = get_default_value(this,field_name)
here in particular, it is always default

2023-11-16 17:45 UTC, abuts commented on herbert_core/configuration/@config_base/config_base.m
> +        %     value = obj.([field_name,'_']);
see previous comment or `config_base` description.

2023-11-20 10:07 UTC, abuts commented
merging as further work depends on this. I hope I've addressed the reviewer comments

2023-11-20 10:07 UTC, merged