Add fitting file-backed tests for Toby/multifit
pace-neutrons/Horace pull request #1424
Opened 2023-12-06 15:17 UTC by oerc0122

Add simple tests to verify file-backed fitting algorithms for use in #760 refactor of Tobyfit and as part of verification of #1420

Fixes #1423

2023-12-07 09:40 UTC, abuts approved these changes
except small noize in tests (which I've fixed) looks good and useful checks performed

2023-12-07 13:15 UTC, cmarooney-stfc requested changes

2023-12-07 13:21 UTC, oerc0122 commented on _test/test_TF_components/test_tobyfit_cuts.m
> +            skipTest("Disabled until #760 implementation of filebacked Tobyfit")
Currently broken, but the test will be useful in developing #760. Current status is to crash due to size mismatch in `tobyfit_*_resconv`. Updated description to clarify.

2023-12-11 17:53 UTC, cmarooney-stfc requested changes
I have added a comment to the main description of the PR saying that the new test_multifit test here is a multifit equivalent of the ones that are skipped here.

Please confirm this or otherwise by modifying the comment appropriately

2023-12-12 10:49 UTC, cmarooney-stfc approved these changes

2023-12-12 17:02 UTC, merged