join is static sqw method
pace-neutrons/Horace pull request #1429
Opened 2023-12-09 17:33 UTC by abuts

This should be looked at after #1428 is merged. 

This is @oerc0122-style PR, containing only one change. `join` opeation for `sqw` object made static and various small changes related to search for join within the code base and fixing various small issues in the code (like typos) identified while looking for join within the code. 

I normally would not do such PR, because such changes are part of development, but because these changes produce working code at this stage, I do not mind making them a separtate PR.

2023-12-11 11:44 UTC, cmarooney-stfc commented on horace_core/sqw/@sqw/join.m
Appreciate that lines 2-3 are not part of your changes but they are maddeningly incomplete. Suggest adding at line 4:
" and should not be used to combine arbitrary sets of sqw objects; the wrong answer will be produced if this is done. For combining arbitrary sets of sqws, use combine_sqw (or appropriate name)"

2023-12-11 12:07 UTC, abuts commented on horace_core/sqw/@sqw/join.m
this is old comment. I will modify it according to current situation

2023-12-11 13:32 UTC, cmarooney-stfc requested changes

2023-12-12 11:48 UTC, abuts commented on horace_core/sqw/PixelData/@PixelDataBase/PixelDataBase.m
> +        % Contains if the array fits area or describes it if the only
somethins strange is happening with my commits -- they are not displayed on PR-s

2023-12-12 14:02 UTC, abuts commented on horace_core/sqw/PixelData/@PixelDataBase/PixelDataBase.m
> +        % Contains if the array fits area or describes it if the only
"contains" if array fits memory or "Describes" if ...

2023-12-13 13:54 UTC, merged

2023-12-13 13:54 UTC, abuts commented
I hope I've clarified all unclear points and here we have very simple changes