save filebacked modes
pace-neutrons/Horace pull request #1452
Opened 2023-12-19 21:15 UTC by abuts

This is part of the modifications for `save` for sqw files prepared to work with various versions of filebacked files. 

The main thing implemented here is `binfile_v4_common.put_new_blocks_values` method which allows saving various changed `sqw` object  components (any level 1-2 field of `sqw` object) defined in `faccess_sqw_v4` loder into existing `sqw` file. 

Started modifying `save` algorithm on the basis of these changes, but this job is not yet completed. 
As it should be working code, worth doing intermediate PR.

2023-12-20 11:01 UTC, cmarooney-stfc requested changes

2023-12-20 17:57 UTC, abuts commented on horace_core/sqw/file_io/class_helpers/@pix_data_block/pix_data_block.m
> +        function obj =calc_obj_size(obj,sqw_obj,nocache,varargin)
This is the disadvantage of revieving changes from web difference :). The method is `pix_data_block` overload of generic `calc_obj_size` method of parent `data_block` and this fact clearly stated in the row 108.  As this row have not changed, you have not noticed it. 

The parent `calc_obj_size` method have changed adding `check_size` input value. As this check does not make sence for `pix_data_block` (`pix.data` are not serialized) the overload ignores this property. But I still have to adhere to the calling interface so need to add `varargin` for code not to throw `too many arguments`

2023-12-20 18:15 UTC, abuts commented on horace_core/sqw/file_io/class_helpers/@data_block/private/calc_obj_size_.m
> +subobj = obj.get_subobj(sqw_obj);
I am not serializing the whole sqw object here. I am pickin up sub-object only (part of `sqw` as `sqw.property.property` i.e. `sqw.experiment_data.instruments`). Method description modified.

2023-12-20 18:21 UTC, abuts commented on horace_core/sqw/file_io/class_helpers/@blockAllocationTable/private/place_undocked_blocks_.m
> +% calculates free spaces left after old blocks were
Difficult to answer something to this. Typo fixed but `clear_ulcocked_blocks` removes blocks with `lock == false` and `place_unDocked_blocks` find places for undocked blocks i.e. blocks with `position == 0` (undocked).

2023-12-20 18:43 UTC, abuts commented on horace_core/sqw/file_io/class_helpers/@blockAllocationTable/private/merge_adjusent_space_.m
> +% when blocks were located one after another. Get continuous chunks of
I am removing merging `contiguous` blocks and creating `continuous` space (without breaks) May be there is better word for this.

2023-12-20 18:53 UTC, abuts commented on horace_core/sqw/file_io/class_helpers/@blockAllocationTable/blockAllocationTable.m
> +            % Should work after clear_unocked_blocks was called, as clear_unocked_blocks
clear unlocked, place undocked

2023-12-21 16:35 UTC, cmarooney-stfc approved these changes

2023-12-23 12:15 UTC, merged