Enforce orthogonal projection for SymopRotation
pace-neutrons/Horace pull request #1515
Opened 2024-01-30 14:36 UTC by oerc0122

As described in #1510, ultimate issue is symmetrising non-orthogonal crystal.

This is checked where the projection is given, but if not provided, the default projection accidentally copies non-orthogonal lattice. 

- Extra check put in `SymopRotation.is_irreducible`
- Ensure any points which lie on the plane of the irreducible zone are not transformed
- Make default projection always orthogonal 

Fixes #1510

2024-01-30 15:58 UTC, cmarooney-stfc requested changes
add comments as discussed

2024-02-01 13:37 UTC, oerc0122 commented on horace_core/sqw/@sqw/symmetrise_sqw.m
>  end
No, but the transformation should be performed in an othogonal basis

2024-04-15 10:42 UTC, cmarooney-stfc requested changes

2024-04-15 10:42 UTC, cmarooney-stfc commented on horace_core/sqw/@sqw/symmetrise_sqw.m
> +                      'angdeg', [90, 90, 90])};
as just discussed, make it clear that this is an orthogonal transformation between these two projections, not changing a projection. Also make it clear why alatt does need to be retained here.

2024-04-15 10:53 UTC, cmarooney-stfc approved these changes

2024-04-15 14:11 UTC, merged