Clarify 4-element binning args
pace-neutrons/Horace pull request #1531
Opened 2024-02-06 14:05 UTC by oerc0122

Improve clarity of meaning for 4th binning arg as reported as confusing by Christian

2024-02-07 11:55 UTC, abuts reviewed
should be reconciled with Re #1508 which havily modified text of this document. Should be merged ASAP then to avoid merge conflicts in nearest future.

2024-03-13 16:17 UTC, cmarooney-stfc requested changes

2024-03-13 16:17 UTC, cmarooney-stfc commented on documentation/user_docs/docs/manual/Cutting_data_of_interest_from_SQW_files_and_objects.rst
> +The most important fields of ``line_proj`` constructor are the fields, which define the
```suggestion
The most important fields of ``line_proj`` constructor are the fields which define the
```
with this comma, there is no intent to limit the scope of fields to the defining scope. The which clause is merely an explanation of the term fields. The comma must be removed to limit the scope

2024-03-13 16:17 UTC, cmarooney-stfc commented on documentation/user_docs/docs/manual/Cutting_data_of_interest_from_SQW_files_and_objects.rst
> +Projection's lattice parameters (``alatt`` and ``angdeg``) are taken within the ``cut`` from source ``sqw`` object.
```suggestion
The projection's lattice parameters (``alatt`` and ``angdeg``) are taken within the ``cut`` from source ``sqw`` object.
```

2024-03-13 16:17 UTC, cmarooney-stfc commented on documentation/user_docs/docs/manual/Cutting_data_of_interest_from_SQW_files_and_objects.rst
>  vector is build in this plane but orthogonal to :math:`e_z` vector.
```suggestion
vector is built in this plane but orthogonal to :math:`e_z` vector.
```

2024-03-13 16:17 UTC, cmarooney-stfc commented on documentation/user_docs/docs/manual/Cutting_data_of_interest_from_SQW_files_and_objects.rst
>  are still available now. ``cut_sqw`` is fully equivalent to ``cut`` except attempt to apply it to
```suggestion
are still available now. ``cut_sqw`` is fully equivalent to ``cut``, except an attempt to apply it to
```

2024-03-13 16:17 UTC, cmarooney-stfc commented on documentation/user_docs/docs/manual/Cutting_data_of_interest_from_SQW_files_and_objects.rst
> +``cut_dnd`` is equivalent to ``cut`` applied to ``dnd`` object or correspondent file. If ``cut_dnd`` is applied
```suggestion
``cut_dnd`` is equivalent to ``cut`` applied to ``dnd`` object or corresponding file. If ``cut_dnd`` is applied
```

2024-04-22 12:47 UTC, merged