fixing sqw_eval for spherical projection
pace-neutrons/Horace pull request #1541
Opened 2024-02-09 17:12 UTC by abuts

bunch of minor bugs fixing `sqw_eval` (and `bose`) for spherical projection.

Nothing more to tell -- unit tests for bug and the fixture.

2024-02-12 11:42 UTC, cmarooney-stfc requested changes
A summary of the changes has  been added to the PR description. Please review. It is still not so clear what fixes point 2 of the issue, what is a bug encountered while dealing with this, and what is just improved efficiency and documentation.

2024-02-12 12:29 UTC, abuts commented on horace_core/sqw/coord_transform/@aProjectionBase/private/transform_pix_to_hkl_.m
> +if ismethod(obj,'ub_inf_legaccy') && ~isempty(obj.ub_inv_legacy) % legacy alignment
good point!

2024-02-12 12:32 UTC, abuts commented on horace_core/sqw/axes_blocks/@AxesBlockBase/private/bin_pixels_.m
> +        reconcile_sizes = true;
hm, do not understand this suggestion. code below needs nbins as `size` and `size`  always 2D array, not [1,1]. The added boolean needed for reconciling row/column transition as it is apparently matters here. (code fails)

2024-02-12 13:30 UTC, abuts commented on herbert_core/utilities/classes/@data_op_interface/binary_op_manager_single.m
> +%             sort pixels with every bin when operation is performed.
this is fundamental feature of Horace, last explained on the first slide of the discussion we have about `page_op`

Pixels in Horace are arranged (sorted) according to bins but within the bin they may be ordered randomly. 
I do not think the comment on particular operation should (or could) describe principal structure of `sqw` object.

2024-02-12 13:36 UTC, abuts commented on herbert_core/utilities/classes/@data_op_interface/binary_op_manager_single.m
> +%             sort pixels with every bin when operation is performed.
actually, it is not difficult to write this again -- just two centences.

2024-02-12 13:42 UTC, abuts commented on _test/test_sqw_pageOpMethods/test_eval.m
> +            spBose = bose(sp_cut,8);
The test verifies that Bose works now. (was failing in the past)
Testing Bose correctness is not the purpose of this ticket as it needs scientific validation. And proper data. Here I took random piece of data and see that Bose works but 0 for this piece. I think the scope of this ticket is already big enough to add scientific validation to it.

2024-02-12 13:44 UTC, abuts commented on herbert_core/utilities/classes/@data_op_interface/data_op_interface.m
> +        w = binary_op_manager_single(w1, w2, op_function_handle,varargin);
I do normally place cemicolumns to declarations. I believe, old code may not have them in some places. 

If you think this is important, we should discuss it, make agreement and follow this agreement.

2024-02-13 10:39 UTC, cmarooney-stfc approved these changes

2024-02-13 10:58 UTC, merged