Make David's requested changes to resconv
pace-neutrons/Horace pull request #1557
Opened 2024-02-20 16:13 UTC by oerc0122

- Move theory to the bottom
- Add necessary semi-colons to example scripts
- Reformat to 100char/line
- Modernisation of `ortho_proj`

2024-03-13 16:04 UTC, cmarooney-stfc requested changes

2024-04-05 13:04 UTC, tgperring commented on documentation/user_docs/docs/user_guide/Resolution_convolution.rst
> +color plots are supported at present):
I propose:
"Finally, Horace can also plot the projection of the resolution ellipsoid over 2D plots of sqw object data or simulations, be they Q-Q  or Q-energy plots. (Plotting the projection of the resolution ellipsoid over 3D plots of sqw data is not supported at present):"

2024-04-05 13:11 UTC, tgperring commented on documentation/user_docs/docs/user_guide/Resolution_convolution.rst
> +from the sample :math:`\mathbf{Q}_0`.
How about adding this sentence sat the end:
"The nominal energy transfer \omega_0 and momentum transfer \mathbf{Q}_0 are the values that assigned to the energy-detector pixel without account of resolution broadening."

2024-04-05 13:23 UTC, tgperring commented on documentation/user_docs/docs/user_guide/Resolution_convolution.rst
> +is used to determine its speed.  The data is binned in ToF and this is converted
CMM: I don't understand your comment. The conversion of the raw data performed by Mantid includes a rebinning of the raw time-of-flight for each detector element into equal sized energy bins. It is at the Mantid data correction and units conversion stage that the energy bin size is set. Typically this is set to be something like 0.5% or 0.25% of the incident energy over the range of energy transfer range of say -0.3*Ei to 0.95*Ei. The precise values for these parameters will most commonly it is set by the instrument scientist in a template Mantid reduction script for any given experiment. The user may then tinker with this script.

2024-04-05 13:45 UTC, cmarooney-stfc commented on documentation/user_docs/docs/user_guide/Resolution_convolution.rst
> +* ``ps`` is a vector of shape parameters. For the ``cuboid`` shape it is a
You are correct to pull me up on the full stop. I think I should have said something like, what if it's not a cuboid shape? Thanks

2024-04-05 13:46 UTC, cmarooney-stfc commented on documentation/user_docs/docs/user_guide/Resolution_convolution.rst
> +(black lines).
It has dawned on me this is a caption for the picture, which I can't see. Sorry. Maybe putting fig.N in front would help in future.

2024-04-05 13:49 UTC, cmarooney-stfc commented on documentation/user_docs/docs/user_guide/Resolution_convolution.rst
> +color plots are supported at present):
Noting no mention of colour in the revised text. Otherwise very readable.

2024-04-05 13:55 UTC, cmarooney-stfc commented on documentation/user_docs/docs/user_guide/Resolution_convolution.rst
> +is used to determine its speed.  The data is binned in ToF and this is converted
TGP: well, you have clarified this well. Binning is done with equal sized energy bins, hence not in ToF as the original text said. In the process it appears that the raw ToF is lost. It should also be said that all this is done in Mantid. But your text is excellently complete and maybe should go in as-is.

2024-06-20 12:26 UTC, merged