Make `sqw@smooth` return `dnd`
pace-neutrons/Horace pull request #1597
Opened 2024-03-07 13:29 UTC by oerc0122

2024-03-13 09:52 UTC, cmarooney-stfc requested changes

2024-03-13 09:52 UTC, cmarooney-stfc commented on horace_core/sqw/@sqw/smooth.m
> +function wout_dnd = smooth(win, varargin)
not part of your change but next line presuming gataway is gateway, not getaway. Having said which, I still don't know what it means

be good to have explicit description of the input and output arguments, so
input win - sqw without pixels. Although is this still a requirement now the output is a guaranteed dnd separate from any pixel data?
input varargin - parameters for the smooth method for dnds
output wout_dnd - dnd object with image pixels smoothed with respect to the image pixels in input win

2024-03-13 09:52 UTC, cmarooney-stfc commented on horace_core/sqw/@sqw/smooth.m
> +wout_dnd = cellfun(@(x) smooth(x, varargin{:}), wout_dnd);
precede with
% apply dnd smooth method to dnd conversion of input win

2024-04-16 15:35 UTC, cmarooney-stfc commented on horace_core/sqw/@sqw/smooth.m
> +%                width = [2,4,5]    % 2, 3, 5 along the 1st, 2nd and 3rd dimensions
make value and comment consistent

2024-04-16 15:37 UTC, cmarooney-stfc commented on _test/test_sqw_class/test_smooth.m
> +            sqw_in_nopix = copy(sqw_in);
```suggestion
            sqw_in_nopix = copy(sqw_in); % nopix anticipates later depixelation
```

2024-04-16 15:39 UTC, oerc0122 commented on horace_core/sqw/@sqw/smooth.m
> +%                width = [2,4,5]    % 2, 3, 5 along the 1st, 2nd and 3rd dimensions
```suggestion
%                width = [2,4,5]    % 2, 4, 5 along the 1st, 2nd and 3rd dimensions
```

2024-04-16 15:42 UTC, merged