gen sqw progress
pace-neutrons/Horace pull request #1669
Opened 2024-05-08 13:08 UTC by abuts

fixes Re #1663. Small addition makes working with gen_sqw so much nicer

2024-05-09 09:09 UTC, oerc0122 commented
Nothing in the description or title tells me what this change is actually doing.

2024-05-09 10:31 UTC, oerc0122 requested changes

2024-05-10 16:27 UTC, abuts commented on herbert_core/classes/data_loaders/@rundata/private/gen_runfiles_.m
> +max_dot_string_length = 50;
may be. There are similar stuff in parallel, but doing so globaly is a bit of a different job. 
This is not parallel and have no relation to it.  As it is small convenience change, its usfulness is justified by its simplicity.

2024-05-10 16:27 UTC, abuts commented on herbert_core/classes/data_loaders/@rundata/private/gen_runfiles_.m
> +function [log_length,cr_printed] = do_print_log(do_print,log_length,max_length)
would agree with this

2024-05-10 18:32 UTC, abuts commented on herbert_core/classes/data_loaders/@rundata/private/gen_runfiles_.m
> +max_dot_string_length = 50;
Would agree on ticket in technical dept

2024-05-10 22:06 UTC, merged