equal_to_tol in serializable and around
pace-neutrons/Horace pull request #1793
Opened 2024-12-19 19:37 UTC by abuts

Resolves Re #1147. 

This PR modifies `equal_to_tol` to use common code where possible in all its overloads, is deployed in serializable and should support hashable or may be easy modified to support it.

2024-12-20 11:11 UTC, cmarooney-stfc requested changes

2024-12-20 11:11 UTC, cmarooney-stfc commented on herbert_core/utilities/maths/equal_to_tol.m
> +function [ok,mess,opt]=equal_to_tol(a,b,varargin)
opt not documented

2024-12-20 14:53 UTC, abuts commented on _test/shared/matlab_xunit/xunit/assertEqual.m
> +%                    provided here. Message can not start with '-' symbol
you should, it is a part of the statement. I tried to make it clearer.

2024-12-22 11:11 UTC, cmarooney-stfc approved these changes

2024-12-22 14:14 UTC, merged