paging for noisify
pace-neutrons/Horace pull request #355
Opened 2020-09-11 13:11 UTC by cmarooney-stfc

Comparing the existing commit for unitary operators in https://github.com/pace-neutrons/Horace/pull/299/commits/2c7af694929dc8cafb2fee648cff35685a10173c, this PR attempts to do the same thing with noisify.m in sqw\@sqw.

noisify.m is modified in line with unary_op_manager.m to replace the call within the loop over elements of w to noisify (this is the Herbert overload of noisify with separate arguments for signal and variance and additional varargin.) As unary_op and do_unary_op do not currently support varargin and as unary_op currently works by using the parent object for signal and variance as their source, these cannot presently be used without modification.

Options appear to be : 
- add varargin to the above unary_op functions; modify the Herbert noisify to accept a single whole object argument while providing a mechanism to disambiguate the overload from the other (arg, varargin) overloads of noisify.
- make an alternative to do_unary_op which does support the current Herbert 3-arg version of noisify.
I have chosen the second option for simplicity - I do not want to start digging into Herbert or finding out how to manage the overload.

The present commit is draft and for review; please could you comment on whether this is a good idea and what misunderstanding there might be in it.

I note I have left off a semi-colon in noisify.m.

2020-09-14 09:07 UTC, hsautessella requested changes
Thanks for this Chris. This is a good start.

I hadn't considered writing a general function for sigvar operations. My initial idea was to write a `PixelData.noisify` function, which may be more straight-forward in this case, since Herbert's `noisify` function is returning 2 arrays of doubles rather than a `sigvar` object.

The documentation of the [Herbert version of `noisify`](https://github.com/pace-neutrons/Herbert/blob/master/herbert_core/utilities/maths/noisify.m#L8) (which is what's really doing the work) says:
```matlab
%   >> [yout,eout] = noisify (y,e)
%           Add noise with Gaussian distribution, with standard deviation
%           = 0.1*(maximum y value)
```
With the code as it is now, we're going to be `noisify`-ing each page using a distribution with a different standard deviation. We need to make sure we're `noisify`-ing using the same distribution on every page.

2020-09-18 10:22 UTC, cmarooney-stfc commented on horace_core/sqw/PixelData/@PixelData/do_sigvar_pair_va_op.m
> +    pix_out.variance = pg_result.e;
Fixed, 2 commits below

2020-09-18 10:23 UTC, cmarooney-stfc commented on horace_core/sqw/PixelData/@PixelData/do_sigvar_pair_va_op.m
> +    pg_result = svpair_op(pix_out.signal, pix_out.variance, varargin{:});
Fixed, 2 commits below

2020-09-18 10:32 UTC, cmarooney-stfc commented
@hsautessella @nickbattam-tessella with commit 715e1d2 above I put in my function for doing the compare. As I mentioned, although this is noisifying the same sqw object twice with the same method (using the old noisify, not my new one), resetting the rng, I get an error from the assert.

2020-09-29 14:02 UTC, cmarooney-stfc commented
Cancelling = abandoning PR; superseded by #386

2020-09-29 14:02 UTC, closed without merging