Update 0002-use-github-for-documentation.md
pace-neutrons/Horace pull request #512
Opened 2021-01-13 15:58 UTC by oerc0122

Update as suggested by #457

2021-01-13 17:31 UTC, cmarooney-stfc requested changes

2021-01-13 17:31 UTC, cmarooney-stfc commented on documentation/adr/0002-use-github-for-documentation.md
>  We will store documentation in the `Horace/documentation` folder and link to this from the the [GitHub Wiki](https://github.com/pace-neutrons/pace-developers/wiki) which is attached to the PACE proje
@oerc0122 Presumably the folder in this project, so add "folder in the Horace Github repository."

2021-01-13 17:31 UTC, cmarooney-stfc commented on documentation/adr/0002-use-github-for-documentation.md
> +The Jenkins pipeline will also build the documentation as a zipped artifact for examination on other builds.
@oerc0122 Not clear what examination on other builds means. What workflow would this imply? I was presuming that zipped artefacts could be unzipped at remote locations for easy access by users also downloading Horace/PACE.

2021-01-13 17:31 UTC, cmarooney-stfc commented on documentation/adr/0002-use-github-for-documentation.md
>  - Documentation will be stored as part of the Horace project [Horace/documentation](https://github.com/pace-neutrons/horace.git).
This link could also be used to deal with my comment on line 24.

2021-01-14 11:49 UTC, hsautessella requested changes
Looks good. Just a couple of things

2021-01-14 11:49 UTC, hsautessella commented on documentation/adr/0002-use-github-for-documentation.md
> +- release pipeline (stable & horace-version)
The release pipelines build release packages, but we don't necessarily release those packages (we do some testing first). Should the Deploy pipeline or some GitHub action deploy releases?

2021-01-14 11:49 UTC, hsautessella commented on documentation/adr/0002-use-github-for-documentation.md
> +The Jenkins will also build the documentation as a zipped artefact on other pipelines.
Perhaps we should add what other pipelines and _why_ they will build the docs (to check that a code/documentation change has not broken the docs build?).

2021-01-14 12:05 UTC, hsautessella approved these changes
👍

2021-01-14 13:08 UTC, cmarooney-stfc approved these changes
Just noting that the rich documentation / source documentation toggle top right toggles between a diff view and a track changes view typora style - so it is possible to see the rendered document from the file changes tab!

2021-01-27 15:21 UTC, merged