Split PixelData into memory and filebacked
pace-neutrons/Horace pull request #891
Opened 2022-11-03 13:50 UTC by oerc0122

Perform a split of the single `PixelData` object which handles both memory-backed and file-backed in one place into `PixelDataMemory` and `PixelDataFileBacked`, both derived from `PixelDataBase`. 

This allows the user to manipulate pix more precisely and also allows developers to independently optimise and change functions without worrying about what might happen to the memory-backed processes. 

Also makes `PixelDataBase.create` choose memory vs. filebacked based on the `hor_config` setting `mem_chunk_size` to unify page sizes across the Horace code.

2022-11-03 17:13 UTC, cmarooney-stfc requested changes

2022-11-15 11:13 UTC, oerc0122 commented on horace_core/sqw/PixelData/@PixelDataMemory/equal_to_tol.m
> +%% EQUAL_TO_TOL Check if two PixelData objects are equal to a given tolerance
This also checks `PixelDataMemory` vs `PixelDataFileBacked`

2022-11-15 11:46 UTC, oerc0122 commented on horace_core/sqw/PixelData/@PixelDataMemory/get_pixels.m
> +%                    property.
What do you mean by "reduce the volume to 2"? This is standard matlab indexing as far as I can tell, with the caveat that you can't use `end`.

2022-11-21 10:59 UTC, abuts commented on horace_core/sqw/file_io/@faccess_sqw_v3/private/get_sqw_footer_.m
> +end
This is crap -- the previous way was much better

2022-11-21 11:00 UTC, abuts approved these changes
Understanding this in details needs much more involvement than I am ready to do.
I do not like a lot of this, including unwrapping error message throwing, which now takes 7 rows of identical code in different places and keeping the class as a handle. 

But as this is clearly step in the right direction, it should be done ASAP

2022-12-09 16:25 UTC, closed without merging